# Generated by Django 3.1.6 on 2021-03-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
