# Generated by Django 3.1.6 on 2021-03-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('registeration_number', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(default='', max_length=100)),
                ('timeslap', models.TimeField(blank=True)),
                ('author', models.CharField(max_length=100)),
                ('Image', models.ImageField(default='', upload_to='mysite/images')),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='number',
        ),
    ]
