# Generated by Django 3.1.5 on 2021-04-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20210401_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='glay_gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='mysite/images')),
            ],
        ),
    ]
