# Generated by Django 3.1.5 on 2021-04-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_glay_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='glay_gallery',
            name='picture_title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
