# Generated by Django 3.1.5 on 2021-04-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_glay_gallery_picture_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glay_gallery',
            name='picture_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
